build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/examples/onepage
	@mkdir  ../../sea-modules/examples/onepage
	@mkdir  ../../sea-modules/examples/onepage/1.0.0
	@cp     dist/*.* ../../sea-modules/examples/onepage/1.0.0
	@echo
	@echo   " deploy to seajs-modules/examples/onepage/1.0.0"
	@echo